baseURL                 = "/"
languageCode            = "en-us"
defaultContentLanguage  = "en"
isMultilingual          = false
pygmentsStyle           = "manni"
pygmentsCodefences      = true
title                   = "Benjamin Ortiz"
theme                   = "sam"
publishDir              = "docs"

[params]
    dateform            = "Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006"
    homepage            = "main"
    favicon             = "favicon.ico"
    # footerText          = "So long and thanks for all the fish"
    description         = "Benjamin Ortiz"
    twitterCard         = "summary_large_image"
    primaryImage        = "tn.png"

[[params.mainMenu]]
    link = "/about"
    text = "hello"

[[params.mainMenu]]
    link = "/posts"
    text = "posts"
